GET http://localhost:3003/api/blogs
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdGNodW1hbiIsImlkIjoiNjBjNzExZTAyMGYwY2IxMDI5OGY0ZWU3IiwiaWF0IjoxNjI0MDA2MDE0fQ.YZliH3ZM1czvJ6foCnIA6sjUP1QFU79nXV0WEG8hHO0
###
DELETE http://localhost:3003/api/blogs/60ca30451e9d980dba08c0e4
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdGNodW1hbiIsImlkIjoiNjBjNzExZTAyMGYwY2IxMDI5OGY0ZWU3IiwiaWF0IjoxNjIzNzg1MDU1fQ.tkJ0msfUM08aUX-zbitiPv9FJHoCgpwTaUGptdp8g7o
###
POST http://localhost:3003/api/blogs
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdGNodW1hbiIsImlkIjoiNjBjNzExZTAyMGYwY2IxMDI5OGY0ZWU3IiwiaWF0IjoxNjIzODYzMjE2fQ.XluHaR-LIyqiuLSTd9OXk960Gplx36rFNRq_C3nwdQQ

{
    "title": "Lamo lamo",
    "author": "Ranjhana",
    "url": "www.desi-movies.com",
    "userId":"60c711e020f0cb10298f4ee7"
    
}
###
PUT  http://localhost:3003/api/blogs/60c72054cf51d3042d9bf1fa
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdGNodW1hbiIsImlkIjoiNjBjNzExZTAyMGYwY2IxMDI5OGY0ZWU3IiwiaWF0IjoxNjIzODYzMjE2fQ.XluHaR-LIyqiuLSTd9OXk960Gplx36rFNRq_C3nwdQQ

{
"title": "In the love of 1000 dreams",
"author": "putali",
"url": "www.mamathelegend",
"likes": 3333
}
