GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/60c20fbb0ea82d2012a283e9

###
POST http://localhost:3003/api/blogs
content-Type: application/json

{
    "title": "summer of 69",
    "author": "Bryan adams",
    "url": "www.bbc.com",
    "likes": 1122,
    "userId":"60c711e020f0cb10298f4ee7"
   
    
}
###
PUT  http://localhost:3003/api/blogs/60bcf08f008e3f0c2188334c
content-Type: application/json

{
    "likes": 2323
}
