GET http://localhost:3003/api/blogs
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdGNodW1hbiIsImlkIjoiNjBjNzExZTAyMGYwY2IxMDI5OGY0ZWU3IiwiaWF0IjoxNjI0MDA2MDE0fQ.YZliH3ZM1czvJ6foCnIA6sjUP1QFU79nXV0WEG8hHO0
###
DELETE http://localhost:3003/api/blogs/612dd88a17b5ec291e5458ef
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtjQmlzc2UiLCJpZCI6IjYwZDlkNWNlMDk4ZTFiMDUyNWQ1ZjYxYyIsImlhdCI6MTYyOTI5NTYyNX0.1UYe3jR8SvCJWagOOHGfCQzBMxA2dkkJNkOcCzdxL_U
###
POST http://localhost:3003/api/blogs
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtjQmlzc2UiLCJpZCI6IjYwZDlkNWNlMDk4ZTFiMDUyNWQ1ZjYxYyIsImlhdCI6MTYyOTI5NTYyNX0.1UYe3jR8SvCJWagOOHGfCQzBMxA2dkkJNkOcCzdxL_U

{
    "title": "Lamo lamo",
    "author": "Ranjhana",
    "url": "www.desi-movies.com",
    "likes":22
    
}
###
PUT  http://localhost:3003/api/blogs/60c72054cf51d3042d9bf1fa
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hdGNodW1hbiIsImlkIjoiNjBjNzExZTAyMGYwY2IxMDI5OGY0ZWU3IiwiaWF0IjoxNjIzODYzMjE2fQ.XluHaR-LIyqiuLSTd9OXk960Gplx36rFNRq_C3nwdQQ

{
"title": "In the love of 1000 dreams",
"author": "putali",
"url": "www.mamathelegend",
"likes": 3333
}
###
POST http://localhost:3003/api/blogs/612ddff417b5ec291e5458f2/comments
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtjQmlzc2UiLCJpZCI6IjYwZDlkNWNlMDk4ZTFiMDUyNWQ1ZjYxYyIsImlhdCI6MTYyOTI5NTYyNX0.1UYe3jR8SvCJWagOOHGfCQzBMxA2dkkJNkOcCzdxL_U

{
    "desc":"Liked the message given by the blog."
    
}
